output-format: json

strictness: medium
test-warnings: true
doc-warnings: true

ignore-paths:
  - docs
  - venv
  - tests

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pycodestyle:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 79

pydocstyle:
  full: true
  disable:
    - D212
    - D213
    - D104

mccabe:
  run: false